repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # ή νεότερη έκδοση
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0
    hooks:
      - id: isort


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: ['types-requests']  # αν έχεις external libs

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-r", "."]
