name: Docker Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image for Python ${{ matrix.python-version }}
        run: |
          docker build \
            -t test-python-${{ matrix.python-version }} \
            --file ./docker/${{ matrix.python-version }}/Dockerfile .


      - name: Run tests in Docker container
        run: |
          docker run --rm test-python-${{ matrix.python-version }}
