name: Multi-OS with Tox


on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            purpose: desktop
          - os: ubuntu-latest
            arch: arm64
            purpose: mobile
          - os: ubuntu-latest
            arch: x64
            purpose: server
          - os: debian-latest
            arch: x64
            purpose: desktop
          - os: debian-latest
            arch: arm64
            purpose: mobile
          - os: debian-latest
            arch: x64
            purpose: server
          - os: fedora-latest
            arch: x64
            purpose: desktop
          - os: fedora-latest
            arch: arm64
            purpose: mobile
          - os: fedora-latest
            arch: x64
            purpose: server
          - os: rocky-latest
            arch: x64
            purpose: desktop
          - os: rocky-latest
            arch: arm64
            purpose: mobile
          - os: rocky-latest
            arch: x64
            purpose: server
          - os: windows-latest
            arch: x64
            purpose: desktop
          - os: windows-latest
            arch: arm64
            purpose: mobile
          - os: windows-latest
            arch: x64
            purpose: server

        # os: [
        #   # Desktop / Server Linux
        #   ubuntu-latest,      # Ubuntu Desktop / Server LTS
        #   debian-latest,      # Debian stable
        #   fedora-latest,      # Fedora Workstation / Server
        #   rocky-latest,       # Rocky Linux (RHEL-based)
          
        #   # Windows
        #   windows-latest,     # Windows 10/11
          
        #   # Mobile / Embedded Linux
        #   android-latest,     # Android emulator / AOSP
        #   raspios-latest,     # Raspberry Pi OS (ARM)
        #   kali-arm-latest     # Kali Linux ARM (pentesting / IoT)
        # ]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
      
        architecture:
          - x64
          - arm64

        purpose:
          - desktop
          - server
          - mobile
          - embedded
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run tests with tox
        run: tox
        env:
          TOXENV: py${{ matrix.python-version }}
          CI: true
