# .github/workflows/docker-image.yml
name: Docker Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: echo "Building on ${{ matrix.os }} with Python ${{ matrix.python-version }}"


      - name: Install tox
        run: pip install tox

      - name: Run tests with tox
        run: tox
        env:
          TOXENV: py${{ matrix.python-version }}
          CI: true
