name: Test Python Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.extract.outputs.versions }}
    steps:
      - name: Fetch versions manifest
        run: curl -s https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json > manifest.json

      - id: extract
        run: |
          versions=$(jq -r '[.[] | select(.stable == true and (.version | startswith("3."))) | .version] | unique | sort | reverse | .[:5]' manifest.json)
          echo "versions=$versions" >> $GITHUB_OUTPUT

  tests:
    needs: get-python-versions
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.get-python-versions.outputs.versions) }}
